// Format: { q: "pytanie", a: ["odp1","odp2","odp3","odp4"], c: indeks_poprawnej }

const QUESTIONS = {

    history: [
        { q: "W którym roku Polska odzyskała niepodległość?", a: ["1916", "1918", "1920", "1922"], c: 1 },
        { q: "Kto był pierwszym królem Polski?", a: ["Mieszko I", "Bolesław Chrobry", "Kazimierz Wielki", "Władysław Łokietek"], c: 1 },
        { q: "W którym roku wybuchła II wojna światowa?", a: ["1937", "1938", "1939", "1940"], c: 2 },
        { q: "W którym roku wybuchła I wojna światowa?", a: ["1912", "1913", "1914", "1915"], c: 2 },
        { q: "Kto był pierwszym człowiekiem w kosmosie?", a: ["Neil Armstrong", "Buzz Aldrin", "Jurij Gagarin", "Alan Shepard"], c: 2 },
        { q: "W którym roku człowiek po raz pierwszy wylądował na Księżycu?", a: ["1967", "1968", "1969", "1970"], c: 2 },
        { q: "Kto odkrył Amerykę dla Europejczyków w 1492 roku?", a: ["Amerigo Vespucci", "Vasco da Gama", "Krzysztof Kolumb", "Ferdynand Magellan"], c: 2 },
        { q: "Kto napisał 'Pana Tadeusza'?", a: ["Juliusz Słowacki", "Adam Mickiewicz", "Zygmunt Krasiński", "Cyprian Norwid"], c: 1 },
        { q: "W którym mieście urodził się Mikołaj Kopernik?", a: ["Kraków", "Gdańsk", "Toruń", "Poznań"], c: 2 },
        { q: "W którym roku odbyła się bitwa pod Grunwaldem?", a: ["1390", "1400", "1410", "1420"], c: 2 },
        { q: "Kto wynalazł druk?", a: ["Leonardo da Vinci", "Johannes Gutenberg", "Galileusz", "Isaac Newton"], c: 1 },
        { q: "Kto namalował Monę Lisę?", a: ["Michał Anioł", "Rembrandt", "Leonardo da Vinci", "Rafael"], c: 2 },
        { q: "W którym roku zakończyła się II wojna światowa?", a: ["1943", "1944", "1945", "1946"], c: 2 },
        { q: "Kim był Józef Piłsudski?", a: ["Pierwszy prezydent RP", "Marszałek Polski", "Pierwszy premier RP", "Dowódca wojsk zaborczych"], c: 1 },
        { q: "W którym roku upadł mur berliński?", a: ["1987", "1988", "1989", "1990"], c: 2 },
        { q: "Który faraon zbudował największą piramidę w Gizie?", a: ["Ramzes II", "Tutanchamon", "Cheops", "Kleopatra"], c: 2 },
        { q: "W którym roku upadło Cesarstwo Zachodniorzymskie?", a: ["376", "410", "476", "529"], c: 2 },
        { q: "Kim był Juliusz Cezar?", a: ["Grecki filozof", "Rzymski wódz i dyktator", "Egipski faraon", "Macedoński król"], c: 1 },
        { q: "Który kraj rozpętał II wojnę światową?", a: ["Włochy", "Japonia", "Niemcy nazistowskie", "Związek Radziecki"], c: 2 },
        { q: "Który kraj jako pierwszy przyznał kobietom prawa wyborcze?", a: ["USA", "Wielka Brytania", "Nowa Zelandia", "Francja"], c: 2 },
        { q: "Kim był Aleksander Wielki?", a: ["Cesarz Rzymu", "Macedoński król i zdobywca", "Grecki filozof", "Perski władca"], c: 1 },
        { q: "Gdzie odbyły się pierwsze nowożytne Igrzyska Olimpijskie?", a: ["Rzym", "Paryż", "Ateny", "Londyn"], c: 2 },
        { q: "W którym roku odbyły się pierwsze nowożytne Igrzyska Olimpijskie?", a: ["1892", "1896", "1900", "1904"], c: 1 },
        { q: "Kim był Leonardo da Vinci?", a: ["Artysta i wynalazca renesansu", "Odkrywca Ameryki", "Papież", "Cesarz Francji"], c: 0 },
        { q: "Co to był renesans?", a: ["Epoka średniowiecza", "Odrodzenie kultury antycznej", "Rewolucja przemysłowa", "Epoka romantyzmu"], c: 1 },
        { q: "Kim był Karol Wielki?", a: ["Władca Franków i pierwszy cesarz Zachodu", "Cesarz Niemiec", "Król Anglii", "Cesarz Bizancjum"], c: 0 },
        { q: "Kiedy rozpoczęła się rewolucja przemysłowa?", a: ["XVII wiek", "XVIII wiek", "XIX wiek", "XX wiek"], c: 1 },
        { q: "Gdzie wybuchła rewolucja francuska?", a: ["Londyn", "Berlin", "Paryż", "Wiedeń"], c: 2 },
        { q: "W którym roku wybuchła rewolucja francuska?", a: ["1769", "1779", "1789", "1799"], c: 2 },
        { q: "Kim była Marie Curie?", a: ["Polska malarka", "Polska fizyczka i chemiczka", "Polska poetka", "Polska królowa"], c: 1 },
        { q: "Co odkryła Marie Curie?", a: ["Penicylinę", "Rad i polon", "Promienie Rentgena", "Elektryczność"], c: 1 },
        { q: "Kto zbudował Koloseum?", a: ["Grecy", "Egipcjanie", "Rzymianie", "Persowie"], c: 2 },
        { q: "Czym było starożytne Koloseum?", a: ["Świątynią", "Amfiteatrem", "Pałacem", "Grobowcem"], c: 1 },
        { q: "Kim był Mikołaj Kopernik?", a: ["Matematykiem", "Astronomem", "Fizykiem", "Biologiem"], c: 1 },
        { q: "Co odkrył Kopernik?", a: ["Grawitację", "Że Ziemia krąży wokół Słońca", "Penicylinę", "Elektryczność"], c: 1 },
        { q: "Kim był Fryderyk Chopin?", a: ["Polskim malarzem", "Polskim kompozytorem", "Polskim pisarzem", "Polskim rzeźbiarzem"], c: 1 },
        { q: "Gdzie urodził się Fryderyk Chopin?", a: ["Kraków", "Warszawa", "Żelazowa Wola", "Poznań"], c: 2 },
        { q: "Kim był Jan Matejko?", a: ["Polskim pisarzem", "Polskim malarzem historycznym", "Polskim muzykiem", "Polskim architektem"], c: 1 },
        { q: "Kto namalował 'Bitwę pod Grunwaldem'?", a: ["Artur Grottger", "Henryk Siemiradzki", "Jan Matejko", "Jacek Malczewski"], c: 2 },
        { q: "Który król 'zastał Polskę drewnianą, a zostawił murowaną'?", a: ["Bolesław Chrobry", "Kazimierz Wielki", "Władysław Jagiełło", "Zygmunt August"], c: 1 },
        { q: "Kiedy żył Kazimierz Wielki?", a: ["1210–1270", "1310–1370", "1410–1470", "1510–1570"], c: 1 },
        { q: "Co to byli Krzyżacy?", a: ["Zakon rycerski", "Plemię słowiańskie", "Dynastia królów", "Armia turecka"], c: 0 },
        { q: "Kiedy Polska wstąpiła do Unii Europejskiej?", a: ["2002", "2003", "2004", "2005"], c: 2 },
        { q: "Kto był pierwszym demokratycznie wybranym prezydentem Polski po 1989?", a: ["Wojciech Jaruzelski", "Lech Wałęsa", "Aleksander Kwaśniewski", "Tadeusz Mazowiecki"], c: 1 },
        { q: "Co to była 'Solidarność'?", a: ["Partia komunistyczna", "Związek zawodowy i ruch opozycyjny", "Organizacja sportowa", "Stowarzyszenie Kościoła"], c: 1 },
        { q: "Kto był założycielem 'Solidarności'?", a: ["Lech Kaczyński", "Tadeusz Mazowiecki", "Lech Wałęsa", "Jan Paweł II"], c: 2 },
        { q: "Kim był Jan Paweł II?", a: ["Papieżem", "Prezydentem", "Premierem", "Kardynałem"], c: 0 },
        { q: "Jak nazywał się Jan Paweł II przed wyborem na papieża?", a: ["Stefan Wyszyński", "Karol Wojtyła", "Józef Glemp", "Adam Sapieha"], c: 1 },
        { q: "W którym roku Jan Paweł II został papieżem?", a: ["1976", "1977", "1978", "1979"], c: 2 },
        { q: "Jak nazywa się polska hymn narodowy?", a: ["Oda do radości", "Mazurek Dąbrowskiego", "Bogurodzica", "Gaude Mater Polonia"], c: 1 },
    ],

    geography: [
        { q: "Jaka jest stolica Polski?", a: ["Kraków", "Gdańsk", "Warszawa", "Wrocław"], c: 2 },
        { q: "Jaka jest stolica Francji?", a: ["Marsylia", "Lyon", "Bordeaux", "Paryż"], c: 3 },
        { q: "Jaka jest stolica Niemiec?", a: ["Hamburg", "Berlin", "Monachium", "Frankfurt"], c: 1 },
        { q: "Jaka jest stolica Włoch?", a: ["Mediolan", "Neapol", "Rzym", "Florencja"], c: 2 },
        { q: "Jaka jest stolica Hiszpanii?", a: ["Barcelona", "Madryt", "Sewilla", "Walencja"], c: 1 },
        { q: "Jaka jest stolica Wielkiej Brytanii?", a: ["Manchester", "Birmingham", "Edynburg", "Londyn"], c: 3 },
        { q: "Jaka jest stolica USA?", a: ["Nowy Jork", "Los Angeles", "Chicago", "Waszyngton"], c: 3 },
        { q: "Jaka jest stolica Rosji?", a: ["Sankt Petersburg", "Moskwa", "Kijów", "Mińsk"], c: 1 },
        { q: "Jaka jest stolica Chin?", a: ["Szanghaj", "Hongkong", "Pekin", "Nankin"], c: 2 },
        { q: "Jaka jest stolica Japonii?", a: ["Osaka", "Kioto", "Tokio", "Hiroszima"], c: 2 },
        { q: "Jaka jest stolica Australii?", a: ["Sydney", "Melbourne", "Brisbane", "Canberra"], c: 3 },
        { q: "Jaka jest stolica Brazylii?", a: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], c: 2 },
        { q: "Jaka jest stolica Kanady?", a: ["Toronto", "Vancouver", "Ottawa", "Montreal"], c: 2 },
        { q: "Jaki jest najwyższy szczyt świata?", a: ["K2", "Kangchenjunga", "Mount Everest", "Lhotse"], c: 2 },
        { q: "W którym kraju leży Mount Everest?", a: ["Indie", "Nepal/Tybet", "Pakistan", "Bhutan"], c: 1 },
        { q: "Jaka jest najdłuższa rzeka świata?", a: ["Amazonka", "Nil", "Jangcy", "Missisipi"], c: 1 },
        { q: "Jaki jest największy ocean świata?", a: ["Atlantycki", "Indyjski", "Arktyczny", "Spokojny"], c: 3 },
        { q: "Jaki jest największy kontynent?", a: ["Afryka", "Ameryka Północna", "Europa", "Azja"], c: 3 },
        { q: "Jaki jest najmniejszy kontynent?", a: ["Europa", "Australia", "Antarktyda", "Ameryka Południowa"], c: 1 },
        { q: "Ile kontynentów ma Ziemia?", a: ["5", "6", "7", "8"], c: 2 },
        { q: "Jaka jest największa pustynia świata?", a: ["Sahara", "Gobi", "Kalahari", "Arabska"], c: 0 },
        { q: "Na jakim kontynencie leży Sahara?", a: ["Azja", "Ameryka", "Afryka", "Australia"], c: 2 },
        { q: "Jaki jest najdłuższy łańcuch górski świata?", a: ["Himalaje", "Andy", "Alpy", "Góry Skaliste"], c: 1 },
        { q: "Jaki jest najgłębszy rów oceaniczny?", a: ["Rów Mariański", "Rów Atacama", "Rów Jawajski", "Rów Puerto Rico"], c: 0 },
        { q: "Jaka jest stolica Ukrainy?", a: ["Lwów", "Charków", "Odessa", "Kijów"], c: 3 },
        { q: "Jaka jest stolica Czech?", a: ["Brno", "Praga", "Pilzno", "Ostrawa"], c: 1 },
        { q: "Jaka jest stolica Węgier?", a: ["Wiedeń", "Bratysława", "Budapeszt", "Bukareszt"], c: 2 },
        { q: "Jaka jest stolica Austrii?", a: ["Wiedeń", "Salzburg", "Innsbruck", "Linz"], c: 0 },
        { q: "Jaka jest stolica Szwecji?", a: ["Oslo", "Kopenhaga", "Helsinki", "Sztokholm"], c: 3 },
        { q: "Jaka jest stolica Norwegii?", a: ["Sztokholm", "Oslo", "Kopenhaga", "Helsinki"], c: 1 },
        { q: "Ile województw ma Polska?", a: ["14", "16", "18", "20"], c: 1 },
        { q: "Jaka jest największa rzeka Polski?", a: ["Wisła", "Odra", "Warta", "Bug"], c: 0 },
        { q: "Jaki jest najwyższy szczyt Polski?", a: ["Kasprowy Wierch", "Giewont", "Rysy", "Śnieżka"], c: 2 },
        { q: "Jakie morze obmywa Polskę od północy?", a: ["Morze Północne", "Morze Bałtyckie", "Morze Czarne", "Morze Śródziemne"], c: 1 },
        { q: "Jakie miasto jest największe w Polsce?", a: ["Kraków", "Łódź", "Warszawa", "Wrocław"], c: 2 },
        { q: "Na granicy których krajów leżą Tatry?", a: ["Polski i Czech", "Polski i Słowacji", "Polski i Niemiec", "Polski i Ukrainy"], c: 1 },
        { q: "Jaka rzeka przepływa przez Kraków?", a: ["Odra", "Wisła", "Warta", "San"], c: 1 },
        { q: "Jaka rzeka przepływa przez Warszawę?", a: ["Odra", "Bug", "Wisła", "Narew"], c: 2 },
        { q: "Jaki kraj jest największy na świecie?", a: ["USA", "Chiny", "Kanada", "Rosja"], c: 3 },
        { q: "Jaki kraj jest najbardziej zaludniony na świecie?", a: ["Chiny", "Indie", "USA", "Indonezja"], c: 1 },
        { q: "Na jakim kontynencie leży Egipt?", a: ["Azja", "Afryka", "Europa", "Bliski Wschód"], c: 1 },
        { q: "Co to jest Amazonka?", a: ["Góra", "Rzeka", "Jezioro", "Pustynia"], c: 1 },
        { q: "Na jakim kontynencie leży Amazonia?", a: ["Afryka", "Azja", "Ameryka Północna", "Ameryka Południowa"], c: 3 },
        { q: "Jaka jest stolica Meksyku?", a: ["Guadalajara", "Monterrey", "Meksyk", "Cancún"], c: 2 },
        { q: "Gdzie leżą Alpy?", a: ["Skandynawia", "Europa Środkowa i Zachodnia", "Bałkany", "Pireneje"], c: 1 },
        { q: "Jakie jest największe jezioro na świecie?", a: ["Bajkał", "Morze Kaspijskie", "Jezioro Górne", "Jezioro Wiktorii"], c: 1 },
        { q: "Jakie jest najgłębsze jezioro świata?", a: ["Bajkał", "Morze Kaspijskie", "Jezioro Górne", "Jezioro Titicaca"], c: 0 },
        { q: "Jaka jest stolica Indii?", a: ["Mumbaj", "Kalkuta", "Nowe Delhi", "Bangalore"], c: 2 },
        { q: "Jaka jest stolica Turcji?", a: ["Stambuł", "Izmir", "Ankara", "Antalya"], c: 2 },
        { q: "Na jakim kontynencie leży Argentyna?", a: ["Ameryka Północna", "Ameryka Środkowa", "Ameryka Południowa", "Afryka"], c: 2 },
        { q: "Jaka jest stolica Argentyny?", a: ["Rio de Janeiro", "Santiago", "Buenos Aires", "Lima"], c: 2 },
    ],

    mathematics: [
        { q: "Ile wynosi 3/4 + 1/4?", a: ["1/2", "1", "5/4", "3/8"], c: 1 },
        { q: "Ile wynosi 1/2 + 1/3?", a: ["2/5", "2/6", "5/6", "3/5"], c: 2 },
        { q: "Ile wynosi 2/3 × 3/4?", a: ["1/2", "5/7", "8/9", "6/7"], c: 0 },
        { q: "Ile wynosi 25% z 80?", a: ["15", "20", "25", "30"], c: 1 },
        { q: "Ile wynosi 50% z 120?", a: ["50", "60", "70", "80"], c: 1 },
        { q: "Ile wynosi 10% z 350?", a: ["30", "35", "40", "45"], c: 1 },
        { q: "Jaki jest obwód kwadratu o boku 5 cm?", a: ["10 cm", "15 cm", "20 cm", "25 cm"], c: 2 },
        { q: "Jaka jest powierzchnia prostokąta o bokach 6 cm i 4 cm?", a: ["20 cm²", "24 cm²", "28 cm²", "32 cm²"], c: 1 },
        { q: "Jaka jest powierzchnia kwadratu o boku 7 cm?", a: ["42 cm²", "49 cm²", "56 cm²", "63 cm²"], c: 1 },
        { q: "Ile wynosi 2³?", a: ["4", "6", "8", "16"], c: 2 },
        { q: "Ile wynosi 5²?", a: ["10", "15", "25", "30"], c: 2 },
        { q: "Ile wynosi √36?", a: ["4", "6", "8", "9"], c: 1 },
        { q: "Ile wynosi √64?", a: ["6", "7", "8", "9"], c: 2 },
        { q: "Która z tych liczb jest pierwsza?", a: ["9", "15", "17", "21"], c: 2 },
        { q: "Ile wynosi 0,5 + 0,7?", a: ["1,0", "1,1", "1,2", "1,3"], c: 2 },
        { q: "Ile wynosi 3,6 ÷ 0,6?", a: ["5", "6", "7", "8"], c: 1 },
        { q: "Ile wynosi 1/4 z 48?", a: ["10", "12", "14", "16"], c: 1 },
        { q: "Jaki jest NWD(12, 18)?", a: ["3", "4", "6", "9"], c: 2 },
        { q: "Jaka jest NWW(4, 6)?", a: ["8", "10", "12", "16"], c: 2 },
        { q: "Ile wynosi obwód trójkąta o bokach 3, 4 i 5 cm?", a: ["10 cm", "11 cm", "12 cm", "13 cm"], c: 2 },
        { q: "Ile wynosi pole trójkąta o podstawie 6 cm i wysokości 4 cm?", a: ["10 cm²", "12 cm²", "14 cm²", "16 cm²"], c: 1 },
        { q: "Ile stopni wynosi suma kątów w trójkącie?", a: ["90°", "120°", "180°", "360°"], c: 2 },
        { q: "Ile stopni wynosi kąt prosty?", a: ["45°", "60°", "90°", "120°"], c: 2 },
        { q: "Ile stopni wynosi pełny obrót?", a: ["90°", "180°", "270°", "360°"], c: 3 },
        { q: "Ile wynosi 15% z 200?", a: ["25", "30", "35", "40"], c: 1 },
        { q: "Jaką liczbę należy pomnożyć przez 7, aby otrzymać 56?", a: ["6", "7", "8", "9"], c: 2 },
        { q: "Ile wynosi (-3) + (-5)?", a: ["-2", "2", "-8", "8"], c: 2 },
        { q: "Ile wynosi (-4) × (-3)?", a: ["-12", "-7", "7", "12"], c: 3 },
        { q: "Ile wynosi (-10) ÷ 2?", a: ["-5", "-4", "4", "5"], c: 0 },
        { q: "Jaka jest wartość x w równaniu x + 7 = 15?", a: ["6", "7", "8", "9"], c: 2 },
        { q: "Jaka jest wartość x w równaniu 3x = 21?", a: ["5", "6", "7", "8"], c: 2 },
        { q: "Ile centymetrów ma 1 metr?", a: ["10", "100", "1000", "10000"], c: 1 },
        { q: "Ile milimetrów ma 1 centymetr?", a: ["5", "10", "100", "1000"], c: 1 },
        { q: "Ile gramów ma 1 kilogram?", a: ["100", "500", "1000", "10000"], c: 2 },
        { q: "Ile mililitrów ma 1 litr?", a: ["10", "100", "1000", "10000"], c: 2 },
        { q: "Ile sekund ma 1 minuta?", a: ["30", "60", "90", "120"], c: 1 },
        { q: "Ile minut ma 1 godzina?", a: ["30", "60", "90", "120"], c: 1 },
        { q: "Ile godzin ma 1 doba?", a: ["12", "20", "24", "30"], c: 2 },
        { q: "Ile dni ma rok przestępny?", a: ["364", "365", "366", "367"], c: 2 },
        { q: "Ile wynosi 30% z 90?", a: ["24", "27", "30", "33"], c: 1 },
        { q: "Ile wynosi 2/5 dziesiętnie?", a: ["0,3", "0,35", "0,4", "0,45"], c: 2 },
        { q: "Które wyrażenie jest największe?", a: ["1/2", "2/3", "3/4", "4/5"], c: 3 },
        { q: "Ile wynosi obwód koła o promieniu 7 cm? (π ≈ 3,14)", a: ["43,96 cm", "44,96 cm", "45,96 cm", "46,96 cm"], c: 0 },
        { q: "Ile wynosi pole koła o promieniu 5 cm? (π ≈ 3,14)", a: ["78,5 cm²", "80,5 cm²", "82,5 cm²", "84,5 cm²"], c: 0 },
        { q: "Ile wynosi średnia arytmetyczna z liczb 4, 6, 8, 10?", a: ["6", "7", "8", "9"], c: 1 },
        { q: "Ile wynosi 1000 – 378?", a: ["612", "622", "632", "642"], c: 1 },
        { q: "Ile wynosi 24 × 5?", a: ["100", "110", "120", "130"], c: 2 },
        { q: "Ile wynosi 144 ÷ 12?", a: ["11", "12", "13", "14"], c: 1 },
        { q: "Jaka jest wartość x w równaniu 2x – 4 = 10?", a: ["5", "6", "7", "8"], c: 2 },
        { q: "Ile wynosi 75% z 200?", a: ["100", "125", "150", "175"], c: 2 },
    ],

    biology: [
        { q: "Ile kości ma dorosły człowiek?", a: ["106", "206", "306", "406"], c: 1 },
        { q: "Jak nazywa się największa kość w organizmie człowieka?", a: ["Kość ramieniowa", "Kość udowa", "Kość piszczelowa", "Kość łokciowa"], c: 1 },
        { q: "Ile zębów ma dorosły człowiek?", a: ["28", "30", "32", "34"], c: 2 },
        { q: "Jak nazywa się czerwony barwnik krwi?", a: ["Melanina", "Chlorofil", "Hemoglobina", "Keratyna"], c: 2 },
        { q: "Jaką grupę krwi nazywamy 'dawcą uniwersalnym'?", a: ["A", "B", "AB", "0"], c: 3 },
        { q: "Jaką grupę krwi nazywamy 'biorcą uniwersalnym'?", a: ["A", "B", "AB", "0"], c: 2 },
        { q: "Ile par chromosomów ma człowiek?", a: ["21", "22", "23", "24"], c: 2 },
        { q: "Co to jest fotosynteza?", a: ["Oddychanie roślin", "Produkcja pokarmu z CO₂ i wody przy udziale światła", "Rozmnażanie roślin", "Pobieranie wody przez korzenie"], c: 1 },
        { q: "Jaki barwnik odpowiada za zieloną barwę liści?", a: ["Melanina", "Karotenoid", "Chlorofil", "Antocyjan"], c: 2 },
        { q: "Ile komór ma serce człowieka?", a: ["2", "3", "4", "5"], c: 2 },
        { q: "Jak nazywa się największy narząd człowieka?", a: ["Płuca", "Wątroba", "Skóra", "Mózg"], c: 2 },
        { q: "Jak nazywa się podstawowa jednostka życia?", a: ["Tkanka", "Organ", "Komórka", "Organizm"], c: 2 },
        { q: "Co to jest DNA?", a: ["Białko", "Kwas dezoksyrybonukleinowy", "Enzym", "Hormon"], c: 1 },
        { q: "Gdzie w komórce jest przechowywane DNA?", a: ["Cytoplazma", "Mitochondrium", "Jądro komórkowe", "Rybosomy"], c: 2 },
        { q: "Co to są bakterie?", a: ["Rośliny", "Grzyby", "Jednokomórkowe organizmy", "Wirusy"], c: 2 },
        { q: "Co to są wirusy?", a: ["Bakterie", "Grzyby", "Niekomórkowe cząstki biologiczne", "Pierwotniaki"], c: 2 },
        { q: "Jak nazywa się nauka o roślinach?", a: ["Zoologia", "Botanika", "Ekologia", "Mikologia"], c: 1 },
        { q: "Jak nazywa się nauka o zwierzętach?", a: ["Botanika", "Zoologia", "Ekologia", "Paleontologia"], c: 1 },
        { q: "Ile nóg ma pająk?", a: ["6", "8", "10", "12"], c: 1 },
        { q: "Ile nóg ma owad?", a: ["4", "6", "8", "10"], c: 1 },
        { q: "Jak oddychają ryby?", a: ["Płucami", "Skrzelami", "Skórą", "Płucami i skrzelami"], c: 1 },
        { q: "Która z poniższych jest ssakiem?", a: ["Łosoś", "Żółw", "Wieloryb", "Orzeł"], c: 2 },
        { q: "Jaka jest największa żyjąca ryba?", a: ["Rekin wielorybi", "Rekin biały", "Ryba-miecz", "Manta"], c: 0 },
        { q: "Jakim zwierzęciem jest kos?", a: ["Ssakiem", "Gadem", "Płazem", "Ptakiem"], c: 3 },
        { q: "Co jedzą rośliny mięsożerne?", a: ["Tylko światło słoneczne", "Owady i małe zwierzęta", "Inne rośliny", "Glebę"], c: 1 },
        { q: "Jak nazywa się podziemna część rośliny?", a: ["Łodyga", "Liść", "Korzeń", "Kwiat"], c: 2 },
        { q: "Do czego służą liście rośliny?", a: ["Do pobierania wody", "Do fotosyntezy i oddychania", "Do rozmnażania", "Do ochrony przed wiatrem"], c: 1 },
        { q: "Jak nazywa się nauka o ekosystemach?", a: ["Botanika", "Zoologia", "Ekologia", "Geologia"], c: 2 },
        { q: "Kto jest producentem w łańcuchu pokarmowym?", a: ["Drapieżniki", "Rośliny", "Roślinożercy", "Grzyby"], c: 1 },
        { q: "Co to jest osmoza?", a: ["Ruch białek", "Ruch wody przez błonę półprzepuszczalną", "Transport aktywny", "Podział komórki"], c: 1 },
        { q: "Co to jest chloroplast?", a: ["Organellum do oddychania", "Organellum do fotosyntezy", "Jądro komórkowe", "Ściana komórkowa"], c: 1 },
        { q: "Ile procent tlenu zawiera powietrze?", a: ["10%", "21%", "33%", "50%"], c: 1 },
        { q: "Jak nazywa się największy ssak lądowy?", a: ["Hipopotam", "Nosorożec", "Słoń afrykański", "Żyrafa"], c: 2 },
        { q: "Jaka jest funkcja mitochondrium?", a: ["Kontrola komórki", "Produkcja energii (ATP)", "Fotosynteza", "Synteza białek"], c: 1 },
        { q: "Jakie zwierzę jest symbolem Australii?", a: ["Koala", "Kangur", "Dziobak", "Emu"], c: 1 },
        { q: "Co jedzą roślinożercy?", a: ["Tylko mięso", "Tylko rośliny", "Mięso i rośliny", "Grzyby"], c: 1 },
        { q: "Co to jest detrytusożerca?", a: ["Drapieżnik", "Roślinożerca", "Organizm żywiący się martwą materią", "Pasożyt"], c: 2 },
        { q: "Jak nazywa się nauka o grzybach?", a: ["Botanika", "Zoologia", "Mikologia", "Ekologia"], c: 2 },
        { q: "Ile kręgów ma kręgosłup człowieka?", a: ["28", "33", "38", "43"], c: 1 },
        { q: "Co to są płuca?", a: ["Narząd trawienny", "Narząd wydalniczy", "Narząd wymiany gazowej", "Narząd krążenia"], c: 2 },
        { q: "Jak dzielimy organizmy ze względu na ciepłotę ciała?", a: ["Ssaki i płazy", "Stałocieplne i zmiennocieplne", "Wodne i lądowe", "Kręgowce i bezkręgowce"], c: 1 },
        { q: "Które zwierzę jest stałocieplne?", a: ["Żmija", "Żaba", "Jaszczurka", "Orzeł"], c: 3 },
        { q: "Jak nazywa się proces oddawania wody przez rośliny?", a: ["Fotosynteza", "Transpiracja", "Osmoza", "Fermentacja"], c: 1 },
        { q: "Co to są chromosomy?", a: ["Białka komórkowe", "Struktury zawierające DNA", "Organella komórkowe", "Enzymy"], c: 1 },
        { q: "Ile procent wody zawiera ciało człowieka?", a: ["40%", "50%", "60%", "70%"], c: 2 },
        { q: "Jaka jest funkcja krwinek czerwonych?", a: ["Walka z infekcjami", "Transport tlenu", "Krzepnięcie krwi", "Produkcja hormonów"], c: 1 },
        { q: "Jaka jest funkcja krwinek białych?", a: ["Transport tlenu", "Krzepnięcie krwi", "Obrona immunologiczna", "Transport składników odżywczych"], c: 2 },
        { q: "Jak nazywa się najtwardszy materiał w organizmie człowieka?", a: ["Kość", "Szkliwo zębów", "Chrząstka", "Paznokieć"], c: 1 },
        { q: "Ile wynosi normalna temperatura ciała człowieka?", a: ["35,5°C", "36,6°C", "37,5°C", "38,0°C"], c: 1 },
        { q: "Jak nazywa się największy ssak morski?", a: ["Rekin wielorybi", "Wieloryb błękitny", "Kaszalot", "Mors"], c: 1 },
    ],

    sport: [
        { q: "Ile graczy ma drużyna piłki nożnej na boisku?", a: ["9", "10", "11", "12"], c: 2 },
        { q: "Ile minut trwa standardowy mecz piłki nożnej?", a: ["80", "90", "100", "120"], c: 1 },
        { q: "Co ile lat odbywa się Mistrzostwo Świata w piłce nożnej?", a: ["2", "4", "6", "8"], c: 1 },
        { q: "Który kraj wygrał najwięcej Mistrzostw Świata w piłce nożnej?", a: ["Niemcy", "Argentyna", "Brazylia", "Włochy"], c: 2 },
        { q: "Ile pól ma szachownica?", a: ["32", "48", "64", "72"], c: 2 },
        { q: "Ile graczy ma drużyna koszykówki na boisku?", a: ["4", "5", "6", "7"], c: 1 },
        { q: "Ile graczy ma drużyna siatkówki na boisku?", a: ["5", "6", "7", "8"], c: 1 },
        { q: "Ile graczy ma drużyna hokeja na lodzie na lodowisku?", a: ["5", "6", "7", "8"], c: 1 },
        { q: "Gdzie odbyły się Letnie Igrzyska Olimpijskie 2024?", a: ["Tokio", "Los Angeles", "Paryż", "Londyn"], c: 2 },
        { q: "Co ile lat odbywają się Letnie Igrzyska Olimpijskie?", a: ["2", "3", "4", "5"], c: 2 },
        { q: "Ile kręgli ustawia się w kręglarstwie?", a: ["8", "9", "10", "11"], c: 2 },
        { q: "Ile graczy ma drużyna rugby union?", a: ["13", "14", "15", "16"], c: 2 },
        { q: "Jaki kraj jest rekordzistą w liczbie złotych medali olimpijskich w historii?", a: ["Rosja", "Chiny", "USA", "Niemcy"], c: 2 },
        { q: "Kim był Muhammad Ali?", a: ["Koszykarzem", "Piłkarzem", "Bokserem", "Zapaśnikiem"], c: 2 },
        { q: "Ile graczy ma drużyna baseballu?", a: ["7", "8", "9", "10"], c: 2 },
        { q: "Jak długi jest maraton?", a: ["36,195 km", "40,195 km", "42,195 km", "44,195 km"], c: 2 },
        { q: "Kim był Michael Jordan?", a: ["Baseballistą", "Koszykarzem", "Piłkarzem", "Tenisistą"], c: 1 },
        { q: "Kim jest Robert Lewandowski?", a: ["Piłkarzem", "Koszykarzem", "Tenisistą", "Lekkoatletą"], c: 0 },
        { q: "Ile złotych medali zdobył Michael Phelps na IO łącznie?", a: ["18", "21", "23", "25"], c: 2 },
        { q: "Kim jest Rafael Nadal?", a: ["Piłkarzem", "Tenisistą", "Koszykarzem", "Pływakiem"], c: 1 },
        { q: "Kim jest Serena Williams?", a: ["Tenisistką", "Koszykarką", "Pływaczką", "Lekkoatletką"], c: 0 },
        { q: "Ile setów gra się w siatkówce (maksymalnie)?", a: ["3", "4", "5", "6"], c: 2 },
        { q: "Do ilu punktów gra się set w siatkówce?", a: ["21", "23", "25", "27"], c: 2 },
        { q: "Na jakim podłożu gra się w tenisa w Wimbledonie?", a: ["Twardym", "Ziemnym", "Trawiastym", "Syntetycznym"], c: 2 },
        { q: "Co to jest 'hat-trick' w piłce nożnej?", a: ["3 gole w jednym meczu", "3 asysty w meczu", "3 żółte kartki", "3 rzuty karne"], c: 0 },
        { q: "Kim był Usain Bolt?", a: ["Bokserem", "Sprinterem", "Pływakiem", "Skoczkiem wzwyż"], c: 1 },
        { q: "Ile wynosi rekord świata Usaina Bolta na 100 m?", a: ["9,58 s", "9,63 s", "9,69 s", "9,72 s"], c: 0 },
        { q: "Kim jest Iga Świątek?", a: ["Koszykarką", "Tenisistką", "Siatkówkarką", "Pływaczką"], c: 1 },
        { q: "Co to jest 'offside' w piłce nożnej?", a: ["Czerwona kartka", "Pozycja spalona", "Rzut wolny", "Aut"], c: 1 },
        { q: "Na jakim dystansie pływa się na 'długim basenie'?", a: ["25 m", "50 m", "75 m", "100 m"], c: 1 },
        { q: "Ile graczy gra jednocześnie w futbolu amerykańskim z jednej strony?", a: ["9", "11", "13", "15"], c: 1 },
        { q: "Ile razy Brazylia wygrała Mistrzostwo Świata w piłce nożnej?", a: ["4", "5", "6", "7"], c: 1 },
        { q: "Który klub wygrał najwięcej Lig Mistrzów UEFA?", a: ["Bayern Monachium", "Barcelona", "Real Madryt", "Manchester United"], c: 2 },
        { q: "Co to jest 'slam dunk' w koszykówce?", a: ["Rzut z dystansu", "Wsad do kosza", "Rzut za 3 punkty", "Rzut wolny"], c: 1 },
        { q: "Ile punktów daje rzut za 3 punkty w koszykówce?", a: ["2", "3", "4", "5"], c: 1 },
        { q: "Kim był Pelé?", a: ["Argentyńskim piłkarzem", "Brazylijskim piłkarzem", "Urugwajskim piłkarzem", "Chilijskim piłkarzem"], c: 1 },
        { q: "Kim był Ayrton Senna?", a: ["Kierowcą Formuły 1", "Piłkarzem", "Bokserem", "Motocyklistą"], c: 0 },
        { q: "Ile godzin trwa wyścig Le Mans?", a: ["6", "12", "24", "48"], c: 2 },
        { q: "Ile razy Polska wygrała Mistrzostwo Świata w piłce nożnej?", a: ["0", "1", "2", "3"], c: 0 },
        { q: "Co to jest 'Grand Slam' w tenisie?", a: ["Wygranie jednego turnieju", "Wygranie wszystkich 4 turniejów wielkoszlemowych w roku", "Pokonanie nr 1 na świecie", "Wygranie Wimbledonu"], c: 1 },
        { q: "Gdzie odbywa się turniej Roland Garros?", a: ["Londyn", "Nowy Jork", "Melbourne", "Paryż"], c: 3 },
        { q: "Gdzie odbywa się Wimbledon?", a: ["Paryż", "Londyn", "Nowy Jork", "Melbourne"], c: 1 },
        { q: "Ile minut trwa kwarta w koszykówce NBA?", a: ["8", "10", "12", "15"], c: 2 },
        { q: "Gdzie odbyły się Letnie IO w 1980 roku?", a: ["Paryż", "Moskwa", "Los Angeles", "Montreal"], c: 1 },
        { q: "Jak długo trwa runda w boksie zawodowym?", a: ["1 minuta", "2 minuty", "3 minuty", "5 minut"], c: 2 },
        { q: "Jaką piłką gra się w rugby?", a: ["Okrągłą", "Owalną", "Sześciokątną", "Trójkątną"], c: 1 },
        { q: "Ile punktów daje przyłożenie w rugby union?", a: ["3", "4", "5", "6"], c: 2 },
        { q: "W jakiej dyscyplinie startuje Anita Włodarczyk?", a: ["Skoku wzwyż", "Rzucie młotem", "Biegu przez płotki", "Skoku w dal"], c: 1 },
        { q: "Ile wynosi masa dysku w rzucie dyskiem mężczyzn?", a: ["1 kg", "2 kg", "3 kg", "4 kg"], c: 1 },
        { q: "Ile graczy ma drużyna polo?", a: ["2", "3", "4", "5"], c: 2 },
    ],
};

const CATEGORY_NAMES = {
    all:         "🌍 Wszystkie kategorie",
    history:     "📜 Historia",
    geography:   "🗺️ Geografia",
    mathematics: "🔢 Matematyka",
    biology:     "🌿 Biologia",
    sport:       "⚽ Sport",
};
